# Snakemake profile for StaG for use on CTMR Gandalf
# Fredrik Boulund 2023

#######################################
# General Snakemake settings
#######################################
#configfile: 
keep-going: False
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
#use-singularity: True
#singularity-prefix: /ceph/db/sing
#singularity-args: "-B /ceph"

#######################################
# Cluster settings
#######################################
cluster:
  mkdir -p /users/sxiao1/wgs_data/kneaddata_test/stag-mwc/slurm_logs/{rule} &&
  sbatch
    --nodes=1
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=/users/sxiao1/wgs_data/kneaddata_test/stag-mwc/slurm_logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
cluster-cancel: scancel
cluster-cancel-nargs: 50
cluster-status: status-sacct.sh
restart-times: 0
max-jobs-per-second: 20
max-status-checks-per-second: 1
latency-wait: 432000
jobs: 500

#######################################
# Resource settings
#######################################
local-cores: 2
default-resources:
  - time="01:00:00"
  - mem_mb=2048
set-threads:
  - fastp=4
  - kraken2_host_removal=8
  - bowtie2_host_removal=8
  - consensus_markers=8
  - print_clades=8
  - kneaddata=8
  - bbcountunique=4
  - sketch=8
  - kaiju=32
  - kraken2=16
  - krakenuniq=24
  - metaphlan=8
  - strainphlan=8
  - bracken=2
  - humann=30
  - groot_align=12
  - align_to_amr=16
  - bbmap=16
  - bowtie2=16
  - assembly=20
  - consolidate_bins=20
  - blobology=20
  - multiqc=1
set-resources:
  - fastp:mem_mb=20480
  - fastp:time="02:00:00"
  - kneaddata:mem_mb=10240
  - kneaddata:time="04:00:00"
  - kraken2_host_removal:mem_mb=10240
  - kraken2_host_removal:time="02:00:00"
  - bowtie2_host_removal:mem_mb=10240
  - bowtie2_host_removal:time="06:00:00"
  - consensus_markers:mem_mb=20480
  - consensus_markers:time="12:00:00"
  - print_clades:mem_mb=20480
  - print_clades:time="12:00:00"
  - extract_markers:mem_mb=20480
  - extract_markers:time="12:00:00"
  - kaiju:mem_mb=10240
  - kaiju:time="10:00:00"
  - kraken2:mem_mb=10240
  - kraken2:time="04:00:00"
  - krakenuniq:mem_mb=10240
  - krakenuniq:time="06:00:00"
  - metaphlan:mem_mb=20480
  - metaphlan:time="24:00:00"
  - strainphlan:mem_mb=20480
  - strainphlan:time="12:00:00"
  - humann:mem_mb=10240
  - humann:time="10:00:00"
  - groot_align:mem_mb=10240
  - groot_align:time="02:00:00"
  - align_to_amr:mem_mb=10240
  - align_to_amr:time="04:00:00"
  - bbmap:mem_mb=10240
  - bbmap:time="04:00:00"
  - bowtie2:mem_mb=10240
  - bowtie2:time="04:00:00"
  - multiqc:time="04:00:00"
  - multiqc:mem_mb=10240
