name: Validate syntax and DAG
on:
  push:
    branches:
      - master
      - develop
  pull_request: []  # Do it on all PRs

jobs:
  validate-syntax-and-dag:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_tag:
          - 'stable'
    container:
      image: snakemake/snakemake:${{ matrix.docker_tag }}
  
    name: Validate syntax and DAG
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create empty input files
        run: |
         ls
         mkdir -pv input
         touch input/test1_1.fq.gz input/test1_2.fq.gz
         touch input/test2_1.fq.gz input/test2_2.fq.gz

      - name: Create placeholder db files
        run: |
         ls 
         mkdir -pv tmpdir
         mkdir -pv db/hg19
         mkdir -pv db/metaphlan
         touch db/hg19/taxo.k2d
         touch db/metaphlan/test.1.bt2
      
      - name: Modify config.yaml
        run: |
         ls
         sed -i 's/assess_depth: False/assess_depth: True/' config/config.yaml
         sed -i 's/sketch_compare: False/sketch_compare: True/' config/config.yaml
         sed -i 's/kaiju: False/kaiju: True/' config/config.yaml
         sed -i 's/kraken2: False/kraken2: True/' config/config.yaml
         sed -i 's/metaphlan: False/metaphlan: True/' config/config.yaml
         sed -i 's/humann: False/humann: True/' config/config.yaml
         sed -i 's/strainphlan: False/strainphlan: True/' config/config.yaml
         sed -i 's/groot: False/groot: True/' config/config.yaml
         sed -i 's/amrplusplus: False/amrplusplus: True/' config/config.yaml
         sed -i 's/assembly: False/assembly: True/' config/config.yaml
         sed -i 's/binning: False/binning: True/' config/config.yaml
         sed -i 's|db_path: \"\"|db_path: \"db/hg19\"|' config/config.yaml
         sed -i 's|db: \"\"|db: \"db\"|' config/config.yaml
         sed -i 's|bt2_db_dir: \"\"|bt2_db_dir: \"db/metaphlan\"|' config/config.yaml
         sed -i 's|bt2_index: \"\"|bt2_index: \"test\"|' config/config.yaml
         sed -i 's|_db: \"\"|_db: \"db\"|' config/config.yaml
         sed -i 's|    index: \"\"|    index: \"db\"|' config/config.yaml
         sed -i 's|kmer_distrib: \"\"|kmer_distrib: \"db\"|' config/config.yaml
         sed -i 's|tmpdir: \"/scratch\"|tmpdir: \"tmpdir\"|' config/config.yaml
         cat config/config.yaml
      
      - name: Run Snakemake
        run: |
         ls
         snakemake --dryrun
        




